os: osx
osx_image: xcode13.4
language: objective-c
xcode_project: UnitTest.xcodeproj # path to your xcodeproj folder
xcode_scheme: UnitTest
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)